<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>a4f5583b-fbb2-4e16-8a9a-e51d236a0163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@title = 'Usabilla Feedback Form' and @src = 'https://d6tizftlrpuof.cloudfront.net/live/i/636919ea54b57677ca6bfee0/37a77851725711b67c85a35ad48eb15983c9b6d6.html?tags=right']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Usabilla Feedback Form&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Usabilla Feedback Form&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fb180bc0-ec1c-4001-a765-172fe85577be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b9e18b9-1cc2-4f14-a9a0-19657ec6444e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f1c9257a-da8b-455d-bf1b-52c1895c25b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dbab2148-7bc6-423a-84c3-9bf86c5c1f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>96096553-3dc7-4f73-a0c3-3680ac3c2db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Usabilla Feedback Form</value>
      <webElementGuid>ca6badd0-e079-4024-af87-b4258243af74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8a649f38-6a8f-442f-aa7c-8503e66e1295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>798ac754-a2e3-4767-90bf-73a13f7b0ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d6tizftlrpuof.cloudfront.net/live/i/636919ea54b57677ca6bfee0/37a77851725711b67c85a35ad48eb15983c9b6d6.html?tags=right</value>
      <webElementGuid>eefde5fb-a297-4992-a1bf-573bffd9acfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;form-style-initialized&quot;]/div[@class=&quot;usabilla__overlay&quot;]/div[1]/iframe[1]</value>
      <webElementGuid>31400207-74b3-440b-b7bf-6a5c0b33cd9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Usabilla Feedback Form' and @src = 'https://d6tizftlrpuof.cloudfront.net/live/i/636919ea54b57677ca6bfee0/37a77851725711b67c85a35ad48eb15983c9b6d6.html?tags=right']</value>
      <webElementGuid>7323ad5c-b143-4afc-93e6-7671c43ec8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/iframe</value>
      <webElementGuid>4889578d-7472-4bdd-9ff9-3600aeb8cbbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
