<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postcode</name>
   <tag></tag>
   <elementGuidId>90acdd56-3cf9-4c98-97f5-f556230b1549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29511' and @id = '28ff82a0-8b55-4dce-8435-eae0624c7643' and @type = 'number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#28ff82a0-8b55-4dce-8435-eae0624c7643</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton[name=&quot;Postcode *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66c1206a-4dd5-40b8-9191-d6f4b54f0999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29511</value>
      <webElementGuid>6846eeae-8996-4078-b147-f1bb2a31d195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>28ff82a0-8b55-4dce-8435-eae0624c7643</value>
      <webElementGuid>d4ff51db-db88-41e2-91f7-58cdc177b1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>abcb0ebd-7568-4733-98da-6250f20811da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>28034c58-5483-4903-a676-d939796f4fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba998e26-fca9-4429-a4de-59e2ad9dfa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;28ff82a0-8b55-4dce-8435-eae0624c7643&quot;)</value>
      <webElementGuid>8a96cfe2-a3d4-4df6-83ba-13fb2faa148b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29511' and @id = '28ff82a0-8b55-4dce-8435-eae0624c7643' and @type = 'number']</value>
      <webElementGuid>bfaa108a-92ba-41fa-a968-70bdcd461dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='28ff82a0-8b55-4dce-8435-eae0624c7643']</value>
      <webElementGuid>e126c7cb-097a-4373-ad42-f73eb6d0f1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29501']/div[9]/div/input</value>
      <webElementGuid>3762af58-315e-431a-8eae-ecc88aeb13db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[9]/div/input</value>
      <webElementGuid>a524c294-5210-4a65-83ed-4371b6610bfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
