<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work phone number</name>
   <tag></tag>
   <elementGuidId>bc494be0-cec6-4c40-9594-d5c17f23010f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29490' and @id = '7a8fccfb-f388-4514-a26a-82b96e18073f' and @type = 'number' and @placeholder = 'Please include your area code and number with no spaces']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7a8fccfb-f388-4514-a26a-82b96e18073f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Work phone number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>760bc089-c96a-4dff-a23d-b3b40ad3d5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29490</value>
      <webElementGuid>50a525d6-d044-4d66-a804-4165d6331305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7a8fccfb-f388-4514-a26a-82b96e18073f</value>
      <webElementGuid>42d2cca3-9c6c-4d9f-8a39-b879eed746bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>98df9521-4491-49f3-bedd-b87e59f0c682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please include your area code and number with no spaces</value>
      <webElementGuid>fd6ae7b9-e69d-4a9e-81d4-c48b23bffe6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>51252dd7-8e7f-4d6a-9ba0-37ce9d1c4f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7a8fccfb-f388-4514-a26a-82b96e18073f&quot;)</value>
      <webElementGuid>92525d1e-66ec-45e7-afde-76f12d32808e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29490' and @id = '7a8fccfb-f388-4514-a26a-82b96e18073f' and @type = 'number' and @placeholder = 'Please include your area code and number with no spaces']</value>
      <webElementGuid>5a3f8032-da8e-4f58-a0a2-1b89846ee376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7a8fccfb-f388-4514-a26a-82b96e18073f']</value>
      <webElementGuid>3b00a568-ce0c-4891-a975-f2d99c04de6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[11]/div/input</value>
      <webElementGuid>0fa6c5f2-0f70-467d-b824-1a668e300365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>be4e3471-15d1-4aa0-8460-7b4b1392e94a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
