<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle name</name>
   <tag></tag>
   <elementGuidId>de1e945a-24a2-43f5-bdf0-31d6212b3d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29486' and @id = 'a36c4a26-2ff7-4e42-a77f-3356b9994975' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a36c4a26-2ff7-4e42-a77f-3356b9994975</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Middle name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebbdeb90-bd70-469d-9214-c2686135e12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29486</value>
      <webElementGuid>b31e5419-050d-4091-8da8-002a53ced493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a36c4a26-2ff7-4e42-a77f-3356b9994975</value>
      <webElementGuid>397e1ea7-0606-4745-a990-55e35961b104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4492e66c-5cd3-4c85-af21-444557106793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>ee999479-6055-4b69-aa1a-d836ff6626b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a36c4a26-2ff7-4e42-a77f-3356b9994975&quot;)</value>
      <webElementGuid>e5d07f93-f46a-4ed8-95b2-38b66749abbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29486' and @id = 'a36c4a26-2ff7-4e42-a77f-3356b9994975' and @type = 'text']</value>
      <webElementGuid>829c8015-bced-4e6b-b5fe-8ee8b400fdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a36c4a26-2ff7-4e42-a77f-3356b9994975']</value>
      <webElementGuid>0294427d-49ee-4037-bb80-c7f1f2e2daa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[4]/div/input</value>
      <webElementGuid>0e6d848f-af56-428a-8846-be2b32e22221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a96f1c06-d47a-474a-b4a2-57073331cb75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
