<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of birth</name>
   <tag></tag>
   <elementGuidId>db36f8fd-80f8-4c5f-a86b-eac3d71fc5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29543' and @id = '4da5f589-b516-48fd-9f8c-50f7cca209e0' and @type = 'text' and @placeholder = 'dd/mm/yyyy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4da5f589-b516-48fd-9f8c-50f7cca209e0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;dd/mm/yyyy&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d9eee38-af74-4aea-a3b7-a1b55ac0b08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29543</value>
      <webElementGuid>ce8bd824-94d9-4791-9e8f-19c7c17813a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4da5f589-b516-48fd-9f8c-50f7cca209e0</value>
      <webElementGuid>d2096d6c-bb25-4f52-a384-317f42b8c8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0ac58c0-380e-453d-87ef-07b2d59b75af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>42c3acc1-053c-4a06-98fa-c6c9aa6b01a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>78635424-dd8a-4dc1-b9b1-a163f219d24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>449ed7d5-6ef3-46db-90b2-84ade40e92a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4da5f589-b516-48fd-9f8c-50f7cca209e0&quot;)</value>
      <webElementGuid>c6ae4f13-c121-4469-9b09-3e683a07bb2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29543' and @id = '4da5f589-b516-48fd-9f8c-50f7cca209e0' and @type = 'text' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>4a1c8831-9e16-4d84-9043-49eb346340d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4da5f589-b516-48fd-9f8c-50f7cca209e0']</value>
      <webElementGuid>39d1f502-2642-42a1-bf95-d6a0825f06a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[6]/div/input</value>
      <webElementGuid>2516df70-4e98-4512-9b65-5d1c79a538c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>ba450985-9b62-45d4-850e-48df85f895a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
