<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suburb</name>
   <tag></tag>
   <elementGuidId>e6798cb9-9950-4d9a-8bf4-661ff0c0850d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29509' and @id = '2aad8f81-a981-44dc-98d4-b62c36138561' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2aad8f81-a981-44dc-98d4-b62c36138561</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Suburb *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8db0dd0d-bd6a-40ec-9047-6c4319fb6293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29509</value>
      <webElementGuid>db6c6079-342d-4ce6-9932-84aba3b3a42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2aad8f81-a981-44dc-98d4-b62c36138561</value>
      <webElementGuid>2f5ef28e-9819-40ab-ab47-e64200b34ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4c21b4c-1279-4ec8-8d77-ad5f12882128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>1dec02a5-3a73-45d4-9d1f-e1a4aa108627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>102a2dde-608f-4769-8f60-c09bb98e64d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2aad8f81-a981-44dc-98d4-b62c36138561&quot;)</value>
      <webElementGuid>e010ce9a-2ffd-4043-9a7d-d668cdb87859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29509' and @id = '2aad8f81-a981-44dc-98d4-b62c36138561' and @type = 'text']</value>
      <webElementGuid>a69d897c-dd5f-489d-809a-7ac6aae60ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='2aad8f81-a981-44dc-98d4-b62c36138561']</value>
      <webElementGuid>49510695-dabd-448b-b871-68df3d9794d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29501']/div[7]/div/input</value>
      <webElementGuid>b9293e1f-b20e-47b9-8608-485aec6e0120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[7]/div/input</value>
      <webElementGuid>e254381f-4d49-4f56-86bb-368425084cb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
