<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street number</name>
   <tag></tag>
   <elementGuidId>ea91bc4e-9b43-4409-87da-9ccf2b05eabe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29540' and @id = 'ef405746-89da-441a-bd55-4f55e7834358' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ef405746-89da-441a-bd55-4f55e7834358</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Street number *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a7ec936-13b1-40fd-9a0c-a3c97720f7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29540</value>
      <webElementGuid>54a6a090-8497-4709-896c-86e426ffd4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ef405746-89da-441a-bd55-4f55e7834358</value>
      <webElementGuid>3d1abbbc-5976-4d6e-b06e-ea41a8f140a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8cb1b59-fc53-4cc7-9f18-50ed1d187230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>be14f37d-78a5-41b7-b845-22b01be35c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0bdd0649-4fd2-4847-918b-c3aed32501cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ef405746-89da-441a-bd55-4f55e7834358&quot;)</value>
      <webElementGuid>084b5e2d-24fb-4ee3-844e-67b63f1b7754</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29540' and @id = 'ef405746-89da-441a-bd55-4f55e7834358' and @type = 'text']</value>
      <webElementGuid>f3e7852f-2ea4-4d66-8c2d-3bf7b806c673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ef405746-89da-441a-bd55-4f55e7834358']</value>
      <webElementGuid>de7606dc-29e0-4fad-9952-74711d871192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29501']/div[5]/div/input</value>
      <webElementGuid>4f44df54-3179-413c-8163-9f98ec0c69b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[5]/div/input</value>
      <webElementGuid>dd217efe-17a8-4a56-ae7c-3291813be297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
