<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile phone number</name>
   <tag></tag>
   <elementGuidId>b2d3c32b-3cfa-4b7a-b4fc-506f3520144b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29489' and @id = '804c0aba-f938-4d9c-b560-a257a26b78c2' and @type = 'number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#804c0aba-f938-4d9c-b560-a257a26b78c2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mobile phone number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0491b818-d71a-4822-beaa-6eb3c59b1768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29489</value>
      <webElementGuid>9f30b13c-bf1a-4420-85ac-73f6b4752481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>804c0aba-f938-4d9c-b560-a257a26b78c2</value>
      <webElementGuid>7e500b82-2287-43b4-8c43-ae2d419fe7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>017dbbab-47ae-47b6-ad12-c1ea4c15bd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>b0b818c1-bf97-4bae-b9d1-4255bd063fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1daec77b-8249-40f0-8120-bafc6be6cfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;804c0aba-f938-4d9c-b560-a257a26b78c2&quot;)</value>
      <webElementGuid>c727f2a4-68f0-4c8c-8d1a-2bfdb4d9cc09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29489' and @id = '804c0aba-f938-4d9c-b560-a257a26b78c2' and @type = 'number']</value>
      <webElementGuid>0fb3afaa-0cf2-4ca9-bc3a-12ee83360f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='804c0aba-f938-4d9c-b560-a257a26b78c2']</value>
      <webElementGuid>da15d33e-f4f8-494e-897d-ab1c07881230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[10]/div/input</value>
      <webElementGuid>076df1cc-ebbd-4a63-82dc-c55ee1a2d77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>1226a1d4-2eaa-4241-9b22-c614ff5f0533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
