<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lot location number</name>
   <tag></tag>
   <elementGuidId>f8650bee-e36d-4a85-a078-4af3e211f4e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29503' and @id = 'db7c917e-cee6-4119-8986-cadcace42076' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#db7c917e-cee6-4119-8986-cadcace42076</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Lot/ location number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>486ac421-2d8b-44b5-8587-e3f97bd09668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29503</value>
      <webElementGuid>76a5152a-e0b0-49db-b403-3eb8faf3f430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>db7c917e-cee6-4119-8986-cadcace42076</value>
      <webElementGuid>5d214674-00ce-41fc-b83a-8e9d82cf99fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3f8991b-7a75-46f8-8421-fa87745bbe50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>421c069e-71a4-4ae3-b14a-960b596aaa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;db7c917e-cee6-4119-8986-cadcace42076&quot;)</value>
      <webElementGuid>cf3e44fe-93ba-4bc6-80ea-3f7d57dee958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29503' and @id = 'db7c917e-cee6-4119-8986-cadcace42076' and @type = 'text']</value>
      <webElementGuid>7c3dda9e-346a-4e85-a987-feedee54b78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='db7c917e-cee6-4119-8986-cadcace42076']</value>
      <webElementGuid>64b64397-9845-4311-8a39-dc122ed1786c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29501']/div[2]/div/input</value>
      <webElementGuid>58a033c2-290d-4c8e-bade-16699a783e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[2]/div/input</value>
      <webElementGuid>8cba505c-f2a2-48d6-ac37-a14e644b8f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
