<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State</name>
   <tag></tag>
   <elementGuidId>06f40711-0779-45f2-81a7-77b70f2948f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29523' and @id = '3b62bbd6-80a3-47a6-9a15-8ae8fe7460a6' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3b62bbd6-80a3-47a6-9a15-8ae8fe7460a6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;State *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf2d9652-da49-4c4a-856a-0d3d366224e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29523</value>
      <webElementGuid>820d4c3d-7562-4515-8b8f-2dc3ff180e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3b62bbd6-80a3-47a6-9a15-8ae8fe7460a6</value>
      <webElementGuid>65ac65ef-7cdc-4d7c-8e50-dbffe1186cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>857a8137-338f-40ca-922f-db679398ad5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>54024764-eea6-440f-a5f3-16e20f7d9606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>WA</value>
      <webElementGuid>939d976d-167b-4615-bc6a-ae5d5c4bb22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3831b26c-babf-4a9e-a634-a14f69b852f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3b62bbd6-80a3-47a6-9a15-8ae8fe7460a6&quot;)</value>
      <webElementGuid>99c09198-1f83-4f44-8996-cb37a8d5a746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29523' and @id = '3b62bbd6-80a3-47a6-9a15-8ae8fe7460a6' and @type = 'text']</value>
      <webElementGuid>9a30d3ca-2103-48ea-85d3-9d973e4c042c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3b62bbd6-80a3-47a6-9a15-8ae8fe7460a6']</value>
      <webElementGuid>26399a19-ba5f-4987-a5f7-d0bc618bb4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29501']/div[8]/div/input</value>
      <webElementGuid>e7bee32f-be0c-4bdc-b884-1dc6320cad1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[8]/div/input</value>
      <webElementGuid>1dccbc75-1244-47b8-9f2f-cc14f1a73490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
