<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Home phone numbe</name>
   <tag></tag>
   <elementGuidId>d4e7ef4a-39a6-4a50-bd6e-d7294426750b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29488' and @id = '98845929-6144-4a2c-a75c-7765097fca7a' and @type = 'number' and @placeholder = 'Please include your area code and number with no spaces']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#98845929-6144-4a2c-a75c-7765097fca7a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Home phone number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20ec7b1e-96f9-4294-bec6-3fb0aa4db8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29488</value>
      <webElementGuid>d7e41a85-e8ee-4061-be5b-3efd07fce399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>98845929-6144-4a2c-a75c-7765097fca7a</value>
      <webElementGuid>add4a0d0-2572-41e7-81d0-81a3b9d5cb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a5296724-49b1-4eb9-9ef4-14ee4a94ceea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please include your area code and number with no spaces</value>
      <webElementGuid>988f9b04-b6d0-47cc-9719-c9bdc0411275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>29350b13-1e16-4e5c-9782-41819924337d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;98845929-6144-4a2c-a75c-7765097fca7a&quot;)</value>
      <webElementGuid>6410a66d-aec3-4921-b521-016d949bd6af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29488' and @id = '98845929-6144-4a2c-a75c-7765097fca7a' and @type = 'number' and @placeholder = 'Please include your area code and number with no spaces']</value>
      <webElementGuid>3afeb7c4-8740-4618-a347-7e5281c85e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='98845929-6144-4a2c-a75c-7765097fca7a']</value>
      <webElementGuid>15a44dda-e906-4a6c-b910-8aa66190280b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[7]/div/input</value>
      <webElementGuid>bc501844-a951-4ad6-b160-fba4eea8ce03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>35a0e664-9985-439c-a5e4-be7d60373153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
