<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street name</name>
   <tag></tag>
   <elementGuidId>20724497-66e1-4f81-bf89-2f2cf51416b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29508' and @id = '4e90e921-f06b-43c1-84c7-8c0b23aa953e' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4e90e921-f06b-43c1-84c7-8c0b23aa953e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Street name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50169eb6-6aac-430a-8ac5-c19889b479c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29508</value>
      <webElementGuid>57272827-b432-463f-be06-8ed42a02f514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4e90e921-f06b-43c1-84c7-8c0b23aa953e</value>
      <webElementGuid>57dca6ec-377e-41e7-8921-48223fee842a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27b1c030-dc2f-48ed-a2cf-29187769f4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>73cced57-1d67-44e9-b300-33533f5422d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d550987-f466-4918-b648-beb945f8caa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4e90e921-f06b-43c1-84c7-8c0b23aa953e&quot;)</value>
      <webElementGuid>1930fce6-ef72-4f91-bb39-a740bbea90b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29508' and @id = '4e90e921-f06b-43c1-84c7-8c0b23aa953e' and @type = 'text']</value>
      <webElementGuid>1a4261a0-6896-4aea-9b43-27a17afb2a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4e90e921-f06b-43c1-84c7-8c0b23aa953e']</value>
      <webElementGuid>a4905939-d737-4f62-901d-69cb4c7edee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29501']/div[6]/div/input</value>
      <webElementGuid>bea6464a-f0e2-4f98-95bb-2996a349581e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[6]/div/input</value>
      <webElementGuid>bd831587-c0eb-4249-ba37-75a1f54c1d57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
