<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address</name>
   <tag></tag>
   <elementGuidId>7c6a5ea1-c205-4e98-a6bd-0659db906594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29491' and @id = 'ea033635-54a5-42ef-ae58-6e554b964ac3' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ea033635-54a5-42ef-ae58-6e554b964ac3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb3c9bca-a2fd-4423-a082-8b6d0fe54071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29491</value>
      <webElementGuid>ba44e8b7-b3bf-4203-92eb-47a59ec3491a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ea033635-54a5-42ef-ae58-6e554b964ac3</value>
      <webElementGuid>6788d4b7-50a1-4cc2-b5c1-c683c200311c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>698a78af-de5c-4c55-8bfa-f0e4abfb8906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>9f37263a-8913-486e-a4c1-d9015d176b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>676751fa-18f7-4bbb-bd06-8611f4b18044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ea033635-54a5-42ef-ae58-6e554b964ac3&quot;)</value>
      <webElementGuid>b9c139f8-97fc-456c-8bcd-57704226c702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29491' and @id = 'ea033635-54a5-42ef-ae58-6e554b964ac3' and @type = 'text']</value>
      <webElementGuid>474a9fd6-b85b-47ac-9592-310ef901e60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ea033635-54a5-42ef-ae58-6e554b964ac3']</value>
      <webElementGuid>6782ffc4-7404-4709-972f-af0758bd51ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[12]/div/input</value>
      <webElementGuid>cf137e4d-39a6-48ef-af43-f65109ef1e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>0a6209eb-964f-490e-9acf-fbdf98e2a6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
