<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer reference number (CRN)</name>
   <tag></tag>
   <elementGuidId>ea926bb9-4ec3-46ef-b9aa-063f88734bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29544' and @id = 'a9083dfd-719d-4314-85f8-0d9ff5606ed4' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a9083dfd-719d-4314-85f8-0d9ff5606ed4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Customer reference number (CRN)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84c8b2f7-9e54-40dc-950b-b96e9d34a8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29544</value>
      <webElementGuid>47d2ea6d-d649-4bfb-bbba-50ff0c6d3851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a9083dfd-719d-4314-85f8-0d9ff5606ed4</value>
      <webElementGuid>7b6e4681-83e0-4c3e-b424-d83ddfccf515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c27dc36-1a3b-4b25-9264-1aa092e598fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>c63586ee-9b8e-4f74-bc56-52c314ae95ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a97bffb-8c9b-485a-945c-8bc69c8af4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a9083dfd-719d-4314-85f8-0d9ff5606ed4&quot;)</value>
      <webElementGuid>acc8aaec-62ef-4019-b9e6-65e27a845e0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29544' and @id = 'a9083dfd-719d-4314-85f8-0d9ff5606ed4' and @type = 'text']</value>
      <webElementGuid>7504c813-00dd-4ad1-8862-629e831fefae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='a9083dfd-719d-4314-85f8-0d9ff5606ed4']</value>
      <webElementGuid>79c87f1f-ee4a-49e9-814e-bdf10a6489e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[16]/div/input</value>
      <webElementGuid>8244f57c-8ebb-4166-9d7a-dd54f02b223d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/input</value>
      <webElementGuid>58058272-c546-4024-a951-adbcdb0173e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
