<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit type</name>
   <tag></tag>
   <elementGuidId>983eaea4-1b15-488d-8739-7c1b49863f8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29505' and @id = '4b0ae8a9-670e-41ee-a17b-5ebab08abce1' and @type = 'text' and @placeholder = 'Apartment, floor, suite etc.']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4b0ae8a9-670e-41ee-a17b-5ebab08abce1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Unit type&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b68ebf29-fd70-40ee-a790-7e59b15fc368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29505</value>
      <webElementGuid>d2ec2b34-9f36-430b-b34c-2b58a1faf56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4b0ae8a9-670e-41ee-a17b-5ebab08abce1</value>
      <webElementGuid>b70a4452-5c27-468c-b7a6-b4fcc1546c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96ab44ef-be60-411d-9b18-0f840b0d29a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apartment, floor, suite etc.</value>
      <webElementGuid>97c1eff5-815d-4e17-b491-aae043f43b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>57b774c6-8a11-47dc-9955-684d4f0247f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4b0ae8a9-670e-41ee-a17b-5ebab08abce1&quot;)</value>
      <webElementGuid>7ed0cbfc-c5a5-43d9-91f0-b99cd4ed00be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29505' and @id = '4b0ae8a9-670e-41ee-a17b-5ebab08abce1' and @type = 'text' and @placeholder = 'Apartment, floor, suite etc.']</value>
      <webElementGuid>0ec7bf7d-875f-4c6f-b5d0-3e0f78f3109c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4b0ae8a9-670e-41ee-a17b-5ebab08abce1']</value>
      <webElementGuid>06339fe7-ca1d-4c87-aff6-51b7336c2a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29501']/div[4]/div/input</value>
      <webElementGuid>3d704da9-98ce-4096-9f6e-72554112667c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[4]/div/input</value>
      <webElementGuid>9a970c48-c0b3-4339-9098-1b7db3d57307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
