<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How many dependent children do you</name>
   <tag></tag>
   <elementGuidId>26e8c9fb-b34c-4a6e-8803-374d25819e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29547' and @id = '8d75fbeb-dfe9-4b78-9e4e-c52735a1e33f' and @type = 'number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8d75fbeb-dfe9-4b78-9e4e-c52735a1e33f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;How many dependent children do you have?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da162484-4b74-4572-bda0-9a202cc21a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29547</value>
      <webElementGuid>9bd1bb76-3b6c-469c-85b5-198b7274ac79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8d75fbeb-dfe9-4b78-9e4e-c52735a1e33f</value>
      <webElementGuid>819c3f8a-977a-43fa-825d-8e0906569d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>294ab9c5-9c43-4756-b464-33a152ca4f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>26e2254e-3e52-482e-940a-63e5871113fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1303cca-38e1-4ca8-ae51-f744b53693e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8d75fbeb-dfe9-4b78-9e4e-c52735a1e33f&quot;)</value>
      <webElementGuid>b9e89b45-e747-493f-8084-6e37129b4f8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29547' and @id = '8d75fbeb-dfe9-4b78-9e4e-c52735a1e33f' and @type = 'number']</value>
      <webElementGuid>86cdcb5e-ed88-4383-8bae-2c4fae3d6102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='8d75fbeb-dfe9-4b78-9e4e-c52735a1e33f']</value>
      <webElementGuid>1dd981f5-8631-44ce-b44e-4e35ace01100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[18]/div/input</value>
      <webElementGuid>057ca076-7b5f-481e-b460-3f8745788db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/input</value>
      <webElementGuid>28495f79-944d-43d1-9171-b7c61a0de80a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
