<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit number</name>
   <tag></tag>
   <elementGuidId>8673be08-5d9d-4c50-9833-09f9a1ed1c65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29538' and @id = '91e0819a-0e77-4c56-80af-a68e1659d70c' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#91e0819a-0e77-4c56-80af-a68e1659d70c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Unit number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>381bce03-2367-46bf-a997-541d9f827a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29538</value>
      <webElementGuid>65fac713-7bea-4cd0-8cab-55c96d19d172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>91e0819a-0e77-4c56-80af-a68e1659d70c</value>
      <webElementGuid>12042387-5bc6-4e18-9159-fb663e2e55b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>779c5335-0c66-4c22-92f2-9d1f2ef9cc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>a7d1e769-9d8a-4ab3-90a7-00948b3cf63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;91e0819a-0e77-4c56-80af-a68e1659d70c&quot;)</value>
      <webElementGuid>51760613-f1b6-4be3-99ba-5e84929534da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29538' and @id = '91e0819a-0e77-4c56-80af-a68e1659d70c' and @type = 'text']</value>
      <webElementGuid>719081a5-6ca3-40d1-964e-661f552190ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='91e0819a-0e77-4c56-80af-a68e1659d70c']</value>
      <webElementGuid>05a9a3be-16d1-42f6-9b32-85eb4311c2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29501']/div[3]/div/input</value>
      <webElementGuid>6b5053c0-09a9-4f13-8104-ea568a1751ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[3]/div/input</value>
      <webElementGuid>c2c7a319-a20a-4dd0-8695-d3135d9e2085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
