<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname</name>
   <tag></tag>
   <elementGuidId>51ea72d0-d556-4f3d-a210-eab04a8f5ea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = '__field_29485' and @id = '50a7e80a-8f12-442b-b3c1-8c5be31626ee' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#50a7e80a-8f12-442b-b3c1-8c5be31626ee</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Surname&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c4102ec-a0ab-4613-88ab-c47035be473b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__field_29485</value>
      <webElementGuid>54d33d45-a6d8-492e-84cb-82276cfb58a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>50a7e80a-8f12-442b-b3c1-8c5be31626ee</value>
      <webElementGuid>a61a9314-3a75-46f0-92bf-562f358934c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>291ad768-28ca-4fd8-ba63-c0217db8dbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input-group__input </value>
      <webElementGuid>090bb748-a3c1-436d-bbbf-3047063b5ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8d302a3-745c-47a3-b21f-1324a5fe5239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;50a7e80a-8f12-442b-b3c1-8c5be31626ee&quot;)</value>
      <webElementGuid>949f8014-abcb-40a2-aada-9a342aac6f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '__field_29485' and @id = '50a7e80a-8f12-442b-b3c1-8c5be31626ee' and @type = 'text']</value>
      <webElementGuid>44e6b99e-4c0f-43ca-b2cc-5077008386fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='50a7e80a-8f12-442b-b3c1-8c5be31626ee']</value>
      <webElementGuid>f591d73e-fd1b-448e-a6ae-4b28c3355e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='__field_29494']/div[5]/div/input</value>
      <webElementGuid>669c3f64-8733-41d0-824a-135b8cebc7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[5]/div/input</value>
      <webElementGuid>c99be437-12e6-4e53-9559-c6899497432e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
